// General-purpose WebMCP Test Agent Runner
// Usage: GEMINI_API_KEY=... node runner.js <URL> [--json-out <path>]
// Discovers document.modelContext tools on any live site, has Gemini
// write test scenarios for each tool's JSON Schema, runs them, and
// reports the result.
//
// Scenarios are ALWAYS generated by Gemini — there is no rule-based or
// otherwise synthetic/mock scenario generator in this file. A tool whose
// scenario generation fails (missing key, API error, bad response) is
// reported as SKIPPED, never silently filled in with made-up data.
//
// --json-out writes the full run (every tool's schema + every scenario's
// actual input/expected/actual, not just the printed summary) as JSON —
// this is what lets another tool (the "Simulate" flow in the VS Code
// extension, replaying this exact run visually in webmcp-agent-ui) reuse
// the real Gemini-authored scenarios instead of asking Gemini again.

const fs = require("fs");
const { chromium } = require("playwright");
const { generateScenariosWithGemini } = require("./gemini-scenarios");
const { ensureReachable, parseTestCredentials } = require("./preflight");

function parseArgs(argv) {
  const args = { url: null, jsonOut: null };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--json-out") args.jsonOut = argv[++i];
    else if (!args.url) args.url = argv[i];
  }
  return args;
}

async function main() {
  const { url, jsonOut } = parseArgs(process.argv.slice(2));
  if (!url) {
    console.error("Usage: GEMINI_API_KEY=... node runner.js <URL> [--json-out <path>]");
    process.exit(1);
  }

  const apiKey = process.env.GEMINI_API_KEY;
  const model = process.env.GEMINI_MODEL || "gemini-2.5-flash";
  if (!apiKey) {
    console.error("ERROR: GEMINI_API_KEY is required. This runner only tests with Gemini-generated");
    console.error("scenarios — there is no mock/rule-based fallback. Set GEMINI_API_KEY and retry.");
    process.exit(1);
  }

  console.log(`\n>> Target: ${url}`);
  const browser = await chromium.launch();
  const page = await browser.newPage();

  const credentials = parseTestCredentials(process.env.WEBMCP_TEST_CREDENTIALS);
  const reach = await ensureReachable(page, url, credentials, (line) => console.log(line));
  if (!reach.ok) {
    console.error(`ERROR: could not reach ${url}: ${reach.reason}`);
    await browser.close();
    process.exit(1);
  }
  let mcpReady = false;
  for (let i = 0; i < 20 && !mcpReady; i++) {
    mcpReady = await page.evaluate(() => !!document.modelContext);
    if (!mcpReady) await page.waitForTimeout(200);
  }
  if (!mcpReady) {
    console.error(`ERROR: No document.modelContext found on ${url} (no WebMCP tool registered).`);
    await browser.close();
    process.exit(1);
  }

  const tools = await page.evaluate(async () => {
    const list = await document.modelContext.getTools();
    return list;
  });

  console.log(`>> Found ${tools.length} tools: ${tools.map(t => t.name).join(", ")}\n`);

  const report = { url, generatedAt: new Date().toISOString(), tools: [] };
  let totalPass = 0, totalCount = 0, skippedTools = 0;

  for (const tool of tools) {
    console.log(`=== TOOL: ${tool.name} ===`);
    console.log(`    ${tool.description || ""}`);

    const toolReport = { name: tool.name, description: tool.description || "", inputSchema: tool.inputSchema || null, scenarios: [], skippedReason: null };
    report.tools.push(toolReport);

    const genResult = await generateScenariosWithGemini(tool, apiKey, model);
    if (!genResult.ok) {
      console.log(`  SKIPPED — Gemini scenario generation failed: ${genResult.reason}`);
      console.log("");
      skippedTools++;
      toolReport.skippedReason = genResult.reason;
      continue;
    }
    const scenarios = genResult.scenarios;
    console.log(`  (Gemini generated ${scenarios.length} scenario(s))`);

    for (const scenario of scenarios) {
      totalCount++;
      const result = await page.evaluate(
        async ({ toolName, input }) => {
          try {
            const res = await document.modelContext.executeTool({ name: toolName }, input);
            return { actualSuccess: !res.isError, text: res.content?.[0]?.text || "" };
          } catch (err) {
            return { actualSuccess: false, text: "Exception: " + err.message };
          }
        },
        { toolName: tool.name, input: scenario.input }
      );

      const pass = result.actualSuccess === scenario.expectSuccess;
      if (pass) totalPass++;
      console.log(
        `  [${pass ? "PASS" : "FAIL"}] ${scenario.name.padEnd(42)} | expected=${scenario.expectSuccess ? "success" : "should be rejected"} | actual="${result.text}"`
      );
      toolReport.scenarios.push({
        name: scenario.name,
        input: scenario.input,
        expectSuccess: scenario.expectSuccess,
        actualSuccess: result.actualSuccess,
        actualText: result.text,
        pass,
      });
    }
    console.log("");
  }

  console.log(`>> TOTAL: ${totalPass}/${totalCount} scenarios passed${skippedTools ? `, ${skippedTools} tool(s) SKIPPED (Gemini failure)` : ""}`);
  await browser.close();

  if (jsonOut) {
    fs.writeFileSync(jsonOut, JSON.stringify(report, null, 2), "utf-8");
    console.log(`>> Wrote run report: ${jsonOut}`);
  }

  if (skippedTools > 0 || tools.length === 0) process.exit(1);
}

main();
